### ISSUE TITLE
Busy loop on unavailable cube

### ISSUE THREAD

**Issue by holgerpieta** [maxill1/node-red-contrib-maxcube2#10]
A while ago my cube stopped responding to commands (as it seems to be doing sometimes) and I had to restart it. Maybe it got a new IP address, but anyway, it wasn't reachable anymore by node-red. At least not until I restarted node-red.
This caused a busy loop in lines 265 of maxcube.js that hogged a full core on my raspi, made the node-red interface unresponsive to the point of being unusable and flooded the log files.
I had to restart node-red to clear the problem.

I guess the fundamental problem is a missing rediscovery of the cube in the maxcube2 library, but even so there should also be a mitigation here.
A good idea would be a counter to retry only a couple of times before giving up.
Also a good idea might be a hold-off, ideally even an exponentially increasing one.

Simplest solution would be a fixed sleep/wait before line 265 (and 276 for that matter). A busy sleep/wait would have been a very bad idea in node-red 0.X, but it might even work in 1.X due to asynchronous scheduling.

Better would be a sleep/wait that hands back control to the scheduler. From what I gather, it might be enough to simply wrap lines 265 and 276 in a time-out: setTimeout( node.maxcubeConnect, 3000 );

**Comment by maxill1** [comment]
Hi, I could try to apply the fixes you propose but I won't be able to test it because i turned my cube into a CUNX to use it with homegear (and i must say it works much better now).

Can you propose a pull request? I will merge and publish if you need it.

**Comment by holgerpieta** [comment]
I've just started digging into JS, so I'm in no position to suggest changes with enough confidence that they'll work.
And in the moment I don't have the infrastructure to test it, either.

**Comment by goofy1988** [comment]
Hello,
thanks for posting this issue. I have the same problem. I would like to test if there is an update for that. That is a pretty big problem for my system because wehen connection gets lost ( instable MAXCube) my whole system is overloaded with the requests to the Max Cube. Thats pretty bad especially when you are not home and are not able to reboot the cube. Please be so kind to solve that issue.  Thank you very much.

Best regards.
Dominik

**Comment by holgerpieta** [comment]
I tried to fix it myself: https://github.com/theWaldschrat/node-red-contrib-maxcube2/commit/cdd4a9b013f4dd368852e1e10f9d8859dd50110d
It solved the problem as in limiting the reconnect attempts to 1 per second, thereby reducing log file spam and CPU hogging.
But it doesn't solve the problem that while it tries to reconnect every second, it never succeeds. Even more so, the reconnect attempts get stuck in a endless loop that cannot be solved except by restarting node-red. Ok, in contrast to before you can actually restart it, because the machine will stay responsive, but it's still not nice.
I'll try to come up with something more useful.

**Comment by goofy1988** [comment]
Hello theWaldschrat,

i´ve tested your changes. Thanks for making your changes public. My sytem is now responsive too. At least one major step.

**Comment by holgerpieta** [comment]
Thanks, good to hear.

But I think I found the real problem:
1. Everything is working fine.
2. Something goes wrong and one of the event handler is called, 'closed' in line 260 or 'error' in line 270.
3. The event handler calls maxcubeConnect() to reestablish the connection.
4. maxcubeConnect() calls maxCube.close() in line 244.
5. Over multiple levels of indirection close causes another 'closed' event to be emitted.
6. The 'closed' event handler is called again and everything repeats.
7. CPU hogging and logfile spamming and node-red doesn't work anymore.
8. Each call increases the stack, so after a while, all memory is used up, the system starts swapping and becomes totally unresponsive.

Maybe @maxill1 knows more.

I have a couple of ideas to solve that, but no more time today to try them. Probably will take a couple of days.

**Comment by goofy1988** [comment]
Well that would be awesome if you figure out a workaround for the problem. Sadfully i cannot follow your explanation, because im not so deep into programming. But i squeeze my thumbs you will solve the problem. Thanks.

**Comment by holgerpieta** [comment]
Turned out the solution was adding a single line, removing the event handler before closing the connection.
Tested it with both cube disconnected from network as well as cube lost power, both worked perfectly.
