### ISSUE TITLE
node RED crash if MAX! Cube is not reachable

### ISSUE THREAD

**Issue by Lyve1981** [maxill1/node-red-contrib-maxcube2#4]
If node red is started and MAX! Cube is not reachable during startup, node red  will except & shutdown.

Problem seems to be that in maxcube.js, self.emit('error'); is called but no one is listening to that error.

**Comment by maxill1** [comment]
Hi ,
some time ago i tried to handle it with the unreleased commit c01212da58c1fbbac87ec7992e8d4707d4ab44c3. 

The release 0.1.3 should include the fix. 

please let me know if it works for you.

**Comment by maxill1** [comment]
fixed in c01212da58c1fbbac87ec7992e8d4707d4ab44c3 and fully handled in 0.2.0 260aef3d7b17bc9997102b21662fa8ae96a62c2c

p.s. related to https://github.com/maxill1/node-red-contrib-maxcube2/issues/5
