### ISSUE TITLE
Maxcube disconnects after a while

### ISSUE THREAD

**Issue by Marosso** [maxill1/node-red-contrib-maxcube2#5]
Hi,

does anybody else experience the maxcube disconnecting after some time (couple of hours)? If I redeploy, it connects again.

Best regards

**Comment by maxill1** [comment]
do you have any other client connection at the same time? (eq3 max! windows software or some other maxcube client)

Please disable https://max.eq-3.de connection too. For me it was causing some trouble and stall.

**Comment by a-bailey** [comment]
Having the same problem.. in the maxcube software I disabled internet access but after about 30 mins to 1 hour the cube shows disconnected status in node-red. Any idea what I could check? I'll try to debug on the weekend

**Comment by Marosso** [comment]
I did not have time to find the underlying issue, but I found a workaround: I put a injection node in the flow, that injects the timestamp (or whatever) into the "maxcube out"-node every 30 minutes. This keeps the connection alive!

**Comment by maxill1** [comment]
My flow exports all the valves status to MQTT and inject a timestamp on
node every minute or so. That's why I never experienced disconnections.


Il giorno mer 5 dic 2018, 18:41 Marosso <notifications@github.com> ha
scritto:

**Comment by a-bailey** [comment]
Can confirm that this solution works, I inject a timestamp into the cube every 25 mins now and experience no more disconnects!

**Comment by maxill1** [comment]
This is a cube protocol limitation and we can't do much on node-red-contrib-maxcube2 side. This should be handled in maxcube/maxcube2 library with some sort of keepalive.

I'm closing this, thank you both.

**Comment by maxill1** [comment]
fixed in 0.2.0 260aef3d7b17bc9997102b21662fa8ae96a62c2c
