### ISSUE TITLE
Having an issue that is stopping node red from starting...

### ISSUE THREAD

**Issue by thedigitalprince** [maxill1/node-red-contrib-maxcube2#8]
Hi,

I have been using it for a while but since the latest updates im getting this issue (below), which stops node red from starting.

wondering if you can shed some light on how to resolve.

Thanks,

Paul

21 Mar 23:51:42 - [info] Starting flows
21 Mar 23:51:43 - [info] [maxcube-server:cba8a6b.b2a0ed8] undefined
21 Mar 23:51:43 - [info] [maxcube-server:cba8a6b.b2a0ed8] Preparing new maxcube connection
21 Mar 23:51:43 - [info] [maxcube-server:cba8a6b.b2a0ed8] Preparing new Maxcube events callback
21 Mar 23:51:43 - [info] [worldmap:6ca29cc8.d1214c] started at /worldmap
21 Mar 23:51:44 - [info] [tcp in:dee105e.f69e8f8] connecting to 192.168.0.233:23
21 Mar 23:51:44 - [info] Started flows
21 Mar 23:51:44 - [info] [udp in:Dynet input] udp listener at 0.0.0.0:12345
21 Mar 23:51:44 - [info] [tcp in:5c1cf17c.d0f978] listening on port 8001
21 Mar 23:51:44 - [info] [udp out:UDP send] udp broadcast ready: 123456 -> 192.168.0.255:12345
21 Mar 23:51:44 - [info] [tcp in:dee105e.f69e8f8] connected to 192.168.0.233:23
21 Mar 23:51:44 - [info] [mqtt-broker:MQTT Broker] Connected to broker: mqtt://localhost:1883
21 Mar 23:51:45 - [red] Uncaught Exception:
21 Mar 23:51:45 - TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at Object.parseCommandMetadata (/home/pi/.node-red/node_modules/maxcube2/maxcube-commandparser.js:66:31)
    at Object.parse (/home/pi/.node-red/node_modules/maxcube2/maxcube-commandparser.js:20:35)
    at MaxCubeLowLevel.<anonymous> (/home/pi/.node-red/node_modules/maxcube2/maxcube.js:53:46)
    at emitOne (events.js:116:13)
    at MaxCubeLowLevel.emit (events.js:211:7)
    at /home/pi/.node-red/node_modules/maxcube2/maxcube-lowlevel.js:43:14
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/maxcube2/maxcube-lowlevel.js:39:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by thedigitalprince** [comment]
It seems my Max cube has had an issue and lost all the valves, i will set it up again but im not sure what caused it.

**Comment by maxill1** [comment]
That happened to me some time ago and I can confirm that the error is
thrown when the cube is not initialized (factory reset).

Sadly my cube keeps resetting itself every 6-8 months... sometimes after a
power failure or a network error.

Anyway next time my cube looses its settings I will try to intercept the
error and emit clearer a message.

**Comment by thedigitalprince** [comment]
Sorry for the awful problem report it was a bit late last night when i realized my whole house was down due to node-red going down. I guess it is an issue parsing the response when there are no valves in the file that is causing it. Do you know a way to force it to update the temperatures apart from switching to auto and back again or changing the values?

**Comment by maxill1** [comment]
no problem, any contribution is appreciated.

I'm sorry but the temperature is updated only when the valve is moving, see max-cube-protocol documentation:
https://github.com/Bouni/max-cube-protocol/blob/master/L-Message.md#actual-temperature-heaterthermostat

I remembered that i made an hotfix for this error on maxcube/maxcube2 library some days ago. I made a PR to the mantainers.
https://github.com/normen/maxcube2/pull/6
https://github.com/ivesdebruycker/maxcube/pull/28
