### ISSUE TITLE
Node maxcube is in desabled state after deployment

### ISSUE THREAD

**Issue by plamend** [maxill1/node-red-contrib-maxcube2#9]
Hi,
Wonderful work, congrats.
I sill can not understand the new future, node disable.
After first configuration and deployment, the node is in a **disabled** state

![image](https://user-images.githubusercontent.com/5188011/68578728-40085d80-047b-11ea-8883-859fe4aae5ce.png)

Is there a special message for enabling?

Thank you.

**Comment by maxill1** [comment]
no, it's just a "pause". You can enable it back only by editing the setting
node and publish it again. I think enabling via published message could be
a nice feature but I migrated to CUNx+homegear (https://community.home-assistant.io/t/converting-a-max-cube-to-cul-cun-to-use-with-home-assistant/74218 and
https://community.openhab.org/t/howto-reflash-max-cube-to-cul-cunx-and-use-with-homegar-and-homematic-binding/55047
)
so I flashed my cube and can't develop/test anymore.

I'm sorry to say that I don't think I will maintain anymore this project.

Il giorno lun 11 nov 2019 alle ore 11:04 plamen danov <
notifications@github.com> ha scritto:

**Comment by plamend** [comment]
Thank you
